name: DashboardTV
options:
  bundleIdPrefix: com.jordankoch
  deploymentTarget:
    tvOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "QRRCB8HB3W"

targets:
  DashboardTV:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: DashboardTV
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jordankoch.DashboardTV
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "DashboardTV"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Jordan Koch. All rights reserved."
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTED_PLATFORMS: appletvos appletvsimulator
        SUPPORTS_MACCATALYST: NO
        SDKROOT: appletvos
